from django.urls import include, path, re_path
from django.views.generic import RedirectView
from . import views
urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("startups/", views.startups_list, name="startups_list"),
    path("startups/<str:startup_id>/", views.startup_detail, name="startup_detail"),
    path("franchises/", views.franchises_list, name="franchises_list"),
    path("franchises/<str:franchise_id>/", views.franchise_detail, name="franchise_detail"),
    path("agencies/", views.agencies_list, name="agencies_list"),
    path("agencies/<str:franchise_id>/", views.agency_detail, name="agency_detail"),
    path("vote-agency/<int:franchise_id>/", views.vote_agency, name="vote_agency"),
    path("specialists/", views.specialists_list, name="specialists_list"),
    path("specialists/<str:specialist_id>/", views.specialist_detail, name="specialist_detail"),
    path("vote-specialist/<int:specialist_id>/", views.vote_specialist, name="vote_specialist"),
    path("edit-franchise/<int:franchise_id>/", views.edit_franchise, name="edit_franchise"),
    path("approve-franchise/<int:franchise_id>/", views.approve_franchise, name="approve_franchise"),
    path("reject-franchise/<int:franchise_id>/", views.reject_franchise, name="reject_franchise"),
    path("approve-agency/<int:franchise_id>/", views.approve_agency, name="approve_agency"),
    path("reject-agency/<int:franchise_id>/", views.reject_agency, name="reject_agency"),
    path("approve-specialist/<int:specialist_id>/", views.approve_specialist, name="approve_specialist"),
    path("reject-specialist/<int:specialist_id>/", views.reject_specialist, name="reject_specialist"),
    path("vote-franchise/<int:franchise_id>/", views.vote_franchise, name="vote_franchise"),
    path("load_similar_franchises/<int:franchise_id>/", views.load_similar_franchises, name="load_similar_franchises"),
    path("load_similar_agencies/<int:franchise_id>/", views.load_similar_agencies, name="load_similar_agencies"),
    path("load_similar_specialists/<int:specialist_id>/", views.load_similar_specialists, name="load_similar_specialists"),
    path("change_owner/<int:startup_id>/", views.change_owner, name="change_owner"),
    path("get_investors/<int:startup_id>/", views.get_investors, name="get_investors"),
    path("add_investor/<int:startup_id>/", views.add_investor, name="add_investor"),
    path(
        "edit_investment/<int:startup_id>/<int:user_id>/",
        views.edit_investment,
        name="edit_investment",
    ),
    path(
        "delete_investment/<int:startup_id>/<int:user_id>/",
        views.delete_investment,
        name="delete_investment",
    ),
    path("change_owner_franchise/<int:franchise_id>/", views.change_owner_franchise, name="change_owner_franchise"),
    path("get_investors_franchise/<int:franchise_id>/", views.get_investors_franchise, name="get_investors_franchise"),
    path("add_investor_franchise/<int:franchise_id>/", views.add_investor_franchise, name="add_investor_franchise"),
    path("edit_investment_franchise/<int:franchise_id>/<int:user_id>/", views.edit_investment_franchise, name="edit_investment_franchise"),
    path("delete_investment_franchise/<int:franchise_id>/<int:user_id>/", views.delete_investment_franchise, name="delete_investment_franchise"),
    path("investments/", views.investments, name="investments"),
    path("news/", views.news, name="news"),
    path("news/<int:article_id>/", views.news_detail, name="news_detail"),
    path("news/<int:article_id>/delete/", views.delete_news, name="delete_news"),
    path("cosmochat/", views.cosmochat, name="cosmochat"),
    path("cosmochat/<int:chat_id>/", views.get_chat_messages, name="get_chat_messages"),
    path("cosmochat/send-message/", views.send_message, name="send_message"),
    path(
        "cosmochat/mark-read/<int:chat_id>/",
        views.mark_messages_read,
        name="mark_messages_read",
    ),
    path("cosmochat/start-chat/<int:user_id>/", views.start_chat, name="start_chat"),
    path(
        "cosmochat/add-participant/<int:chat_id>/",
        views.add_participant,
        name="add_participant",
    ),
    path("cosmochat/leave-chat/<int:chat_id>/", views.leave_chat, name="leave_chat"),
    path(
        "cosmochat/create-group-chat/",
        views.create_group_chat,
        name="create_group_chat",
    ),
    path(
        "cosmochat/available-users-for-chat/<int:chat_id>/",
        views.available_users_for_chat,
        name="available_users_for_chat",
    ),
    path("cosmochat/rename-chat/<int:chat_id>/", views.rename_chat, name="rename_chat"),
    path("cosmochat/available_users/", views.available_users, name="available_users"),
    path("cosmochat/start-deal/<int:chat_id>/", views.start_deal, name="start_deal"),
    path("profile/", views.profile, name="profile"),
    path("profile/delete-avatar/", views.delete_avatar, name="delete_avatar"),
    path("profile/<int:user_id>/", views.profile, name="user_profile"),
    path("create-startup/", views.create_startup, name="create_startup"),
    path("create-franchise/", views.create_franchise, name="create_franchise"),
    path("create-agency/", views.create_agency, name="create_agency"),
    path("create-specialist/", views.create_specialist, name="create_specialist"),
    path(
        "create-startup/success/",
        views.startup_creation_success,
        name="startup_creation_success",
    ),
    path("edit-startup/<int:startup_id>/", views.edit_startup, name="edit_startup"),
    path("moderator-main/", views.main_page_moderator, name="main_page_moderator"),
    path("investor-main/", views.investor_main, name="investor_main"),
    path("startuper-main/", views.startuper_main, name="startuper_main"),
    path("moderator-dashboard/", views.moderator_dashboard, name="moderator_dashboard"),
    path(
        "approve-startup/<int:startup_id>/",
        views.approve_startup,
        name="approve_startup",
    ),
    path(
        "reject-startup/<int:startup_id>/", views.reject_startup, name="reject_startup"
    ),
    path("vote-startup/<int:startup_id>/", views.vote_startup, name="vote_startup"),
    path("invest/<int:startup_id>/", views.invest, name="invest"),
    path("search-suggestions/", views.search_suggestions, name="search_suggestions"),
    path("global-search/", views.global_search, name="global_search"),
    path("planetary-system/", views.planetary_system, name="planetary_system"),
    path("my_startups/", views.my_startups, name="my_startups"),
    path("my_startups/download-report/", views.download_startups_report, name="download_startups_report"),
    path(
        "load_similar_startups/<int:startup_id>/",
        views.load_similar_startups,
        name="load_similar_startups",
    ),
    path("deals/", views.deals_view, name="deals_view"),
    path("deals/approve/<int:chat_id>/", views.approve_deal, name="approve_deal"),
    path("deals/reject/<int:chat_id>/", views.reject_deal, name="reject_deal"),
    path("notifications/", views.notifications_view, name="notifications_page"),
    path("support/", views.support_page_view, name="support"),
    path("support/orders/", views.support_orders_view, name="support_orders"),
    path(
        "support/ticket/<int:ticket_id>/",
        views.support_ticket_detail,
        name="support_ticket_detail",
    ),
    path(
        "support/ticket/<int:ticket_id>/close/",
        views.close_support_ticket,
        name="close_support_ticket",
    ),
    path(
        "support/ticket/<int:ticket_id>/update-status/",
        views.update_ticket_status,
        name="update_ticket_status",
    ),
    path("support/contact/", views.support_contact_view, name="support_contact"),
    path(
        "telegram-bot-webhook/<str:token>/",
        views.telegram_webhook,
        name="telegram_webhook",
    ),
    path(
        "favicon.ico",
        RedirectView.as_view(url="/static/images/favicon.png", permanent=True),
    ),
    path("faq/", views.faq_page_view, name="faq"),
    path("contacts/", views.contacts_page_view, name="contacts"),
    path("legal/", views.legal, name="legal"),
    path(
        "chats/find_or_create/<int:recipient_id>/",
        views.find_or_create_chat,
        name="find_or_create_chat",
    ),
    path(
        "delete-message/<int:message_id>/", views.delete_message, name="delete_message"
    ),
    path("delete-comment/startup/<int:comment_id>/", views.delete_startup_comment, name="delete_startup_comment"),
    path("delete-comment/franchise/<int:comment_id>/", views.delete_franchise_comment, name="delete_franchise_comment"),
    path("delete-comment/agency/<int:comment_id>/", views.delete_agency_comment, name="delete_agency_comment"),
    path("delete-comment/specialist/<int:comment_id>/", views.delete_specialist_comment, name="delete_specialist_comment"),
    path(
        "remove-participant/<int:chat_id>/",
        views.remove_participant,
        name="remove_participant",
    ),
    path(
        "cosmochat/<int:chat_id>/messages/",
        views.get_chat_messages,
        name="get_chat_messages_dynamic",
    ),
]
