# Generated by Django 5.1.6 on 2025-05-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newslikes_newsviews_alter_uservotes_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uservotes',
            table='startup_votes',
        ),
    ]
