# Generated by Django 5.1.6 on 2025-05-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_uservotes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startups',
            options={'managed': True},
        ),
    ]
