# Generated by Django 5.1.6 on 2025-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_startups_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startups",
            name="planet_bottom_color",
        ),
        migrations.RemoveField(
            model_name="startups",
            name="planet_middle_color",
        ),
        migrations.RemoveField(
            model_name="startups",
            name="planet_top_color",
        ),
        # migrations.AddField(
        #     model_name='startups',
        #     name='direction',
        #     field=models.ForeignKey(blank=True, db_column='direction_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.directions'),
        # ),
        # migrations.AddField(
        #     model_name='startups',
        #     name='owner',
        #     field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AddField(
            model_name="startups",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='startups',
        #     name='stage',
        #     field=models.ForeignKey(blank=True, db_column='stage_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.startupstages'),
        # ),
        # migrations.AddField(
        #     model_name='startups',
        #     name='status_id',
        #     field=models.ForeignKey(blank=True, db_column='status_id', default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.reviewstatuses'),
        # ),
        migrations.AddField(
            model_name="startups",
            name="terms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
