# Generated by Django 5.1.6 on 2025-05-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supportorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportOrder',
        ),
    ]
