# Generated by Django 5.1.6 on 2025-06-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_startups_planet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversations',
            options={'managed': True},
        ),
    ]
