# Generated by Django 5.1.6 on 2025-06-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_chatconversations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversations',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
