# Generated by Django 5.1.6 on 2025-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_chatconversations_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
