# Generated by Django 5.0.6 on 2025-06-20 14:25

from django.db import migrations

def create_telegram_social_app(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')

    # Получаем текущий сайт (предполагаем, что он один и с ID=1)
    # Если у вас другой ID сайта, измените его здесь.
    try:
        site = Site.objects.get(pk=1)
    except Site.DoesNotExist:
        # Если сайта нет, можно создать его или выбрать другой подход
        # Например, если вы используете `www.greatideas.ru`
        site, _ = Site.objects.get_or_create(domain='www.greatideas.ru', name='www.greatideas.ru')

    # Токен вашего Telegram бота
    bot_token = '7843250850:AAEL8hapR_WVcG2mMNUhWvK-I0DMYG042Ko'

    # Создаем или обновляем SocialApp для Telegram
    social_app, created = SocialApp.objects.update_or_create(
        provider='telegram',
        defaults={
            'name': 'Telegram',
            'client_id': bot_token,
            'secret': '' # Для Telegram secret key не требуется
        }
    )

    # Привязываем приложение к сайту
    social_app.sites.add(site)
    social_app.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_users_telegram_email_users_telegram_id_and_more'),
        # Добавляем зависимость от 'socialaccount' и 'sites', чтобы модели были доступны
        ('socialaccount', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_telegram_social_app),
    ]
