# Generated by Django 5.0.6 on 2025-06-20 14:45

from django.db import migrations

def update_domain(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(pk=1)
        site.domain = 'www.greatideas.ru'
        site.name = 'www.greatideas.ru'
        site.save()
    except Site.DoesNotExist:
        # Если по какой-то причине сайта с pk=1 нет, создадим его
        Site.objects.create(pk=1, domain='www.greatideas.ru', name='www.greatideas.ru')

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_telegram_social_app'),
        # Требуется зависимость от 'sites', чтобы модель была доступна
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_domain),
    ]
