# Generated by Django 4.2.13 on 2025-07-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_filestorage_original_file_name_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.entitytypes'),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.filetypes'),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.startups'),
        ),
        migrations.AddField(
            model_name='users',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='vk_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
