# Generated by Django 4.2.13 on 2025-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_filestorage_entity_type_filestorage_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='vk_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
