# Generated by Django 4.2.13 on 2025-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_franchisecomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'franchise_categories',
                'managed': True,
            },
        ),
    ]
